
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let me=null,clients=[],lastAI="";
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const money=n=>Number(n||0).toLocaleString()+"원";
async function api(url,opts={}){const r=await fetch(url,{...opts,headers:{...(opts.body instanceof FormData?{}:{"Content-Type":"application/json"}),...(opts.headers||{})}});const ct=r.headers.get("content-type")||"";const d=ct.includes("json")?await r.json():await r.text();if(!r.ok)throw new Error(d.error||d||"오류");return d}
function modal(title,body){$("#modalTitle").textContent=title;$("#modalBody").innerHTML=body;$("#modal").classList.remove("hidden")}
function closeModal(){$("#modal").classList.add("hidden")}$("#closeModal").onclick=closeModal;
function pageHead(t,s,a=""){return `<div class="pagehead"><div><h1>${t}</h1><div class="muted small">${s}</div></div><div class="actions">${a}</div></div>`}
const menusAdmin=[["dashboard","대시보드"],["clients","고객사"],["users","사용자"],["documents","회사자료"],["ai","AI 직원"],["leads","영업 CRM"],["opportunities","지원·입찰"],["tickets","고객응대"],["reports","경영보고"],["results","AI 결과물"],["usage","AI 사용량"],["automations","자동화"]];
const menusCustomer=[["dashboard","대시보드"],["documents","회사자료"],["ai","AI 직원"],["leads","영업 CRM"],["opportunities","지원·입찰"],["tickets","고객응대"],["reports","경영보고"],["results","AI 결과물"]];
async function login(){try{await api("/api/login",{method:"POST",body:JSON.stringify({email:$("#email").value,password:$("#password").value})});await boot()}catch(e){$("#loginMsg").textContent=e.message}}
async function boot(){try{me=await api("/api/me");clients=await api("/api/clients");$("#login").classList.add("hidden");$("#app").classList.remove("hidden");$("#who").textContent=me.email;$("#profile").innerHTML=`<b>${esc(me.name)}</b><div class="muted small">${me.role}${me.client_id?` · ${esc(clients[0]?.name||"")}`:""}</div>`;const m=me.role==="admin"?menusAdmin:menusCustomer;$("#nav").innerHTML=m.map((x,i)=>`<button class="${i===0?"active":""}" data-page="${x[0]}">${x[1]}</button>`).join("");$$("#nav button").forEach(b=>b.onclick=()=>showPage(b.dataset.page));showPage("dashboard")}catch{$("#app").classList.add("hidden");$("#login").classList.remove("hidden")}}
function showPage(id){$$(".page").forEach(x=>x.classList.remove("active"));$("#"+id).classList.add("active");$$("#nav button").forEach(x=>x.classList.toggle("active",x.dataset.page===id));render(id)}
async function render(id){await ({dashboard,clients:renderClients,users:renderUsers,documents,ai,leads,opportunities,tickets,reports,results,usage,automations}[id]||dashboard)()}
async function dashboard(){const d=await api("/api/dashboard");$("#dashboard").innerHTML=pageHead("운영 대시보드","실제 DB 기준 현황")+`<div class="grid g4"><div class="card"><div class="muted small">고객사</div><div class="metric">${d.clients}</div></div><div class="card"><div class="muted small">영업 파이프라인</div><div class="metric">${money(d.pipeline)}</div><div class="muted small">${d.leads}건</div></div><div class="card"><div class="muted small">회사자료</div><div class="metric">${d.docs}</div></div><div class="card"><div class="muted small">이번달 AI</div><div class="metric">${d.usage}</div></div></div>`}
const clientForm=(c={})=>`<div class="form2"><div><label>회사명 *</label><input id="f_name" value="${esc(c.name)}"></div><div><label>사업자번호</label><input id="f_biz_no" value="${esc(c.biz_no)}"></div><div><label>업종</label><input id="f_industry" value="${esc(c.industry)}"></div><div><label>담당자</label><input id="f_contact" value="${esc(c.contact)}"></div><div><label>직책</label><input id="f_position" value="${esc(c.position)}"></div><div><label>이메일</label><input id="f_email" value="${esc(c.email)}"></div><div><label>전화</label><input id="f_phone" value="${esc(c.phone)}"></div><div><label>주소</label><input id="f_address" value="${esc(c.address)}"></div><div><label>홈페이지</label><input id="f_website" value="${esc(c.website)}"></div><div><label>플랜</label><select id="f_plan">${["BASIC","PRO","CARE","ENTERPRISE"].map(x=>`<option ${x===c.plan?"selected":""}>${x}</option>`).join("")}</select></div><div><label>상태</label><select id="f_status">${["Trial","Active","Paused","Cancelled"].map(x=>`<option ${x===c.status?"selected":""}>${x}</option>`).join("")}</select></div><div><label>월관리비</label><input id="f_monthly_fee" type="number" value="${c.monthly_fee||0}"></div><div><label>AI 한도</label><input id="f_monthly_ai_limit" type="number" value="${c.monthly_ai_limit||100}"></div><div><label>계약시작일</label><input id="f_start_date" type="date" value="${c.start_date||""}"></div><div><label>갱신일</label><input id="f_renewal_date" type="date" value="${c.renewal_date||""}"></div></div><label>회사설명</label><textarea id="f_summary">${esc(c.summary)}</textarea><label>메모</label><textarea id="f_notes">${esc(c.notes)}</textarea><button class="btn primary" id="saveClient">저장</button>`;
async function renderClients(){clients=await api("/api/clients");$("#clients").innerHTML=pageHead("고객사 관리","상세·수정·삭제·계약관리",me.role==="admin"?`<button class="btn primary" onclick="editClient()">+ 고객사</button>`:"")+`<div class="card"><table><thead><tr><th>회사</th><th>업종</th><th>담당자</th><th>플랜</th><th>상태</th><th>월관리</th><th></th></tr></thead><tbody>${clients.map(c=>`<tr><td><b>${esc(c.name)}</b><br><span class="muted">${esc(c.biz_no||"")}</span></td><td>${esc(c.industry)}</td><td>${esc(c.contact)}<br>${esc(c.phone)}</td><td>${c.plan}</td><td>${c.status}</td><td>${money(c.monthly_fee)}</td><td>${me.role==="admin"?`<button class="btn sm" onclick="editClient('${c.id}')">수정</button> <button class="btn sm danger" onclick="del('/api/clients/${c.id}',renderClients)">삭제</button>`:""}</td></tr>`).join("")}</tbody></table></div>`}
window.editClient=async id=>{const c=id?clients.find(x=>x.id===id):{};modal(id?"고객사 수정":"고객사 추가",clientForm(c));$("#saveClient").onclick=async()=>{const keys=["name","biz_no","industry","contact","position","email","phone","address","website","plan","status","monthly_fee","monthly_ai_limit","start_date","renewal_date","summary","notes"],b={};keys.forEach(k=>b[k]=$("#f_"+k).value);await api(id?`/api/clients/${id}`:"/api/clients",{method:id?"PUT":"POST",body:JSON.stringify(b)});closeModal();await renderClients()}}
async function renderUsers(){const u=await api("/api/users");$("#users").innerHTML=pageHead("사용자 관리","관리자/고객 계정과 고객사 연결",`<button class="btn primary" onclick="editUser()">+ 사용자</button>`)+`<div class="card"><table><thead><tr><th>이름</th><th>이메일</th><th>역할</th><th>고객사</th><th>상태</th><th></th></tr></thead><tbody>${u.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.email)}</td><td>${x.role}</td><td>${esc(clients.find(c=>c.id===x.client_id)?.name||"-")}</td><td>${x.active?"Active":"Inactive"}</td><td><button class="btn sm" onclick='editUser("${x.id}")'>수정</button> <button class="btn sm danger" onclick="del('/api/users/${x.id}',renderUsers)">삭제</button></td></tr>`).join("")}</tbody></table></div>`;window._users=u}
window.editUser=id=>{const x=id?window._users.find(u=>u.id===id):{};modal(id?"사용자 수정":"사용자 추가",`<div class="form2"><div><label>이름</label><input id="u_name" value="${esc(x.name)}"></div><div><label>이메일</label><input id="u_email" value="${esc(x.email)}"></div><div><label>비밀번호 ${id?"(변경시에만)":""}</label><input id="u_password" type="password"></div><div><label>전화</label><input id="u_phone" value="${esc(x.phone)}"></div><div><label>역할</label><select id="u_role"><option ${x.role==="admin"?"selected":""}>admin</option><option ${x.role!=="admin"?"selected":""}>customer</option></select></div><div><label>고객사</label><select id="u_client_id"><option value="">없음/전체</option>${clients.map(c=>`<option value="${c.id}" ${x.client_id===c.id?"selected":""}>${esc(c.name)}</option>`).join("")}</select></div></div><label>메모</label><textarea id="u_notes">${esc(x.notes)}</textarea><label><input id="u_active" style="width:auto" type="checkbox" ${x.active!==0?"checked":""}> 활성</label><br><button class="btn primary" id="saveUser">저장</button>`);$("#saveUser").onclick=async()=>{const b={name:$("#u_name").value,email:$("#u_email").value,password:$("#u_password").value,phone:$("#u_phone").value,role:$("#u_role").value,client_id:$("#u_client_id").value||null,notes:$("#u_notes").value,active:$("#u_active").checked};await api(id?`/api/users/${id}`:"/api/users",{method:id?"PUT":"POST",body:JSON.stringify(b)});closeModal();renderUsers()}}
async function documents(){const a=await api("/api/documents");$("#documents").innerHTML=pageHead("회사자료","PC 파일 업로드·다운로드·AI 학습(RAG)",`<button class="btn primary" onclick="editDoc()">+ 자료 업로드</button>`)+`<div class="card"><table><thead><tr><th>고객사</th><th>자료</th><th>분류</th><th>파일</th><th>상태</th><th></th></tr></thead><tbody>${a.map(d=>`<tr><td>${esc(clients.find(c=>c.id===d.client_id)?.name||"")}</td><td><b>${esc(d.name)}</b><br><span class="muted">${esc(d.summary)}</span></td><td>${esc(d.category)}</td><td>${esc(d.file_name||"-")}<br><span class="muted small">${d.file_size?Math.round(d.file_size/1024)+" KB":""}</span></td><td><span class="pill ${d.status==="Ready"?"ok":"warn"}">${d.status}</span></td><td><button class="btn sm" onclick="location.href='/api/documents/${d.id}/download'">다운로드</button> <button class="btn sm" onclick="ingest('${d.id}')">AI학습</button> <button class="btn sm" onclick='editDoc("${d.id}")'>수정</button> <button class="btn sm danger" onclick="del('/api/documents/${d.id}',documents)">삭제</button></td></tr>`).join("")}</tbody></table></div>`;window._docs=a}
window.editDoc=id=>{const d=id?window._docs.find(x=>x.id===id):{};modal(id?"자료 수정":"회사자료 업로드",`${me.role==="admin"?`<label>고객사</label><select id="d_client">${clients.map(c=>`<option value="${c.id}" ${d.client_id===c.id?"selected":""}>${esc(c.name)}</option>`).join("")}</select>`:""}<label>자료명</label><input id="d_name" value="${esc(d.name)}"><label>분류</label><select id="d_category">${["회사소개","제품자료","제안서","FAQ","업무매뉴얼","기술자료","가격정책","기타"].map(x=>`<option ${x===d.category?"selected":""}>${x}</option>`).join("")}</select>${id?`<label>상태</label><select id="d_status">${["Uploaded","Processing","Ready","Failed"].map(x=>`<option ${x===d.status?"selected":""}>${x}</option>`).join("")}</select>`:`<label>컴퓨터 파일</label><input id="d_file" type="file">`}<label>설명</label><textarea id="d_summary">${esc(d.summary)}</textarea><button class="btn primary" id="saveDoc">저장</button>`);$("#saveDoc").onclick=async()=>{if(id){await api(`/api/documents/${id}`,{method:"PUT",body:JSON.stringify({name:$("#d_name").value,category:$("#d_category").value,status:$("#d_status").value,summary:$("#d_summary").value})})}else{const f=new FormData();f.append("client_id",me.role==="admin"?$("#d_client").value:me.client_id);f.append("name",$("#d_name").value);f.append("category",$("#d_category").value);f.append("summary",$("#d_summary").value);if($("#d_file").files[0])f.append("file",$("#d_file").files[0]);await api("/api/documents",{method:"POST",body:f})}closeModal();documents()}}
window.ingest=async id=>{try{await api(`/api/documents/${id}/ingest`,{method:"POST"});alert("AI 지식베이스에 연결했습니다.");documents()}catch(e){alert(e.message)}}

function renderStructured(r){
 let h="";
 if(r.executive_summary)h+=`<div class="card" style="margin-bottom:10px"><h3>핵심 요약</h3><p>${esc(r.executive_summary)}</p></div>`;
 for(const s of (r.sections||[]))h+=`<div class="card" style="margin-bottom:10px"><h3>${esc(s.heading||"내용")}</h3>${s.body?`<p>${esc(s.body)}</p>`:""}${(s.bullets||[]).length?`<ul>${s.bullets.map(b=>`<li>${esc(b)}</li>`).join("")}</ul>`:""}</div>`;
 if(r.email?.body)h+=`<div class="card" style="margin-bottom:10px"><h3>이메일 완성문안</h3><b>${esc(r.email.subject||"")}</b><p style="white-space:pre-wrap">${esc(r.email.body)}</p></div>`;
 if(r.followup_email?.body)h+=`<div class="card" style="margin-bottom:10px"><h3>후속 이메일</h3><b>${esc(r.followup_email.subject||"")}</b><p style="white-space:pre-wrap">${esc(r.followup_email.body)}</p></div>`;
 if(r.call_script)h+=`<div class="card" style="margin-bottom:10px"><h3>콜 스크립트</h3><p>${esc(r.call_script.opening||"")}</p><ul>${(r.call_script.questions||[]).map(x=>`<li><b>질문:</b> ${esc(x)}</li>`).join("")}${(r.call_script.objection_handling||[]).map(x=>`<li><b>반론대응:</b> ${esc(x)}</li>`).join("")}</ul><p>${esc(r.call_script.closing||"")}</p></div>`;
 if(r.action_plan?.length)h+=`<div class="card" style="margin-bottom:10px"><h3>실행계획</h3><table><thead><tr><th>업무</th><th>담당</th><th>기한</th><th>메모</th></tr></thead><tbody>${r.action_plan.map(a=>`<tr><td>${esc(a.step)}</td><td>${esc(a.owner)}</td><td>${esc(a.due)}</td><td>${esc(a.note)}</td></tr>`).join("")}</tbody></table></div>`;
 if(r.checklist?.length)h+=`<div class="card" style="margin-bottom:10px"><h3>체크리스트</h3>${r.checklist.map(x=>`<div>☐ ${esc(typeof x==="string"?x:JSON.stringify(x))}</div>`).join("")}</div>`;
 if(r.slides?.length)h+=`<div class="card"><h3>제안서 슬라이드 구성 (${r.slides.length}장)</h3>${r.slides.map((s,i)=>`<div style="border-bottom:1px solid #213a58;padding:10px 0"><b>${i+1}. ${esc(s.title)}</b>${s.subtitle?`<div class="muted">${esc(s.subtitle)}</div>`:""}<ul>${(s.bullets||[]).map(b=>`<li>${esc(b)}</li>`).join("")}</ul></div>`).join("")}</div>`;
 return h||`<div class="card">결과 데이터가 없습니다.</div>`;
}
async function ai(){
 $("#ai").innerHTML=pageHead("AI 직원 - 완성 결과물 생성","요청을 세부 조건으로 입력하고 결과를 파일로 저장·다운로드합니다.")+`
 <div class="grid g2">
 <div class="card">
 <label>고객사</label><select id="aiClient">${clients.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join("")}</select>
 <label>AI 직원</label><select id="aiRole"><option>AI 영업사원</option><option>AI 문서비서</option><option>AI 정보조사원</option><option>AI 제안서 기획자</option></select>
 <label>결과물 종류</label><select id="aiDeliverable"><option>영업 제안/메일 패키지</option><option>업무 보고서</option><option>회의록/업무문서</option><option>조사·검토 보고서</option><option>제안서/PPT 구성안</option><option>실행계획서</option></select>
 <label>목적</label><input id="aiGoal" placeholder="예: 신규 제조고객과 데모미팅을 잡기">
 <label>대상/수신자</label><input id="aiAudience" placeholder="예: 제조기업 대표이사">
 <label>배경/상황</label><textarea id="aiBackground" placeholder="현재 상황, 고객 문제, 이전 상담내용 등을 자세히 입력"></textarea>
 <label>핵심 요구사항</label><textarea id="aiRequirements" placeholder="반드시 포함해야 할 내용, 조건, 강조점"></textarea>
 <div class="form2"><div><label>톤</label><select id="aiTone"><option>전문적</option><option>설득적</option><option>친근하고 명확함</option><option>공공기관 문체</option><option>임원 보고 문체</option></select></div><div><label>분량</label><select id="aiLength"><option>상세</option><option>보통</option><option>간결</option></select></div></div>
 <button class="btn primary" onclick="generateArtifact()">완성 결과물 생성</button>
 <p class="muted small">회사자료를 먼저 'AI학습'하면 해당 고객사의 자료를 검색해 결과물에 반영합니다.</p>
 </div>
 <div><div id="artifactStatus" class="muted small" style="margin-bottom:8px">아직 생성된 결과물이 없습니다.</div><div id="artifactPreview"></div></div>
 </div>`;
}
window.generateArtifact=async()=>{
 const b={client_id:$("#aiClient").value,role:$("#aiRole").value,deliverable_type:$("#aiDeliverable").value,goal:$("#aiGoal").value,audience:$("#aiAudience").value,background:$("#aiBackground").value,requirements:$("#aiRequirements").value,tone:$("#aiTone").value,length:$("#aiLength").value};
 if(!b.goal&&!b.background&&!b.requirements)return alert("목적, 배경 또는 요구사항을 입력하세요.");
 $("#artifactStatus").textContent="AI가 세부 결과물을 작성하고 있습니다...";
 $("#artifactPreview").innerHTML=`<div class="card">처리 중...</div>`;
 try{
  const d=await api("/api/ai/generate",{method:"POST",body:JSON.stringify(b)});
  window._currentResult=d.id;
  $("#artifactStatus").innerHTML=`<b>${esc(d.title)}</b> · 저장 완료`;
  $("#artifactPreview").innerHTML=`<div class="actions" style="margin-bottom:10px">
   <a class="btn primary" href="/api/results/${d.id}/export?format=docx">DOCX 다운로드</a>
   <a class="btn" href="/api/results/${d.id}/export?format=pptx">PPTX 다운로드</a>
   <a class="btn" href="/api/results/${d.id}/export?format=txt">TXT 다운로드</a>
   <a class="btn" href="/api/results/${d.id}/export?format=csv">CSV 다운로드</a>
   <a class="btn" href="/api/results/${d.id}/export?format=json">JSON 다운로드</a>
   </div>${renderStructured(d.result)}`;
 }catch(e){$("#artifactStatus").textContent="오류";$("#artifactPreview").innerHTML=`<div class="card">${esc(e.message)}</div>`}
}
async function results(){
 const a=await api("/api/results");
 $("#results").innerHTML=pageHead("AI 결과물 보관함","생성된 결과물을 다시 열고 DOCX·PPTX·TXT·CSV·JSON으로 다운로드합니다.")+
 `<div class="card"><table><thead><tr><th>생성일</th><th>고객사</th><th>AI 직원</th><th>결과물</th><th>제목</th><th>다운로드</th><th></th></tr></thead><tbody>${a.map(x=>`<tr><td>${esc(x.created_at)}</td><td>${esc(clients.find(c=>c.id===x.client_id)?.name||"")}</td><td>${esc(x.role)}</td><td>${esc(x.deliverable_type||"")}</td><td><button class="btn sm" onclick="viewResult('${x.id}')">${esc(x.title)}</button></td><td><a class="btn sm" href="/api/results/${x.id}/export?format=docx">DOCX</a> <a class="btn sm" href="/api/results/${x.id}/export?format=pptx">PPTX</a> <a class="btn sm" href="/api/results/${x.id}/export?format=txt">TXT</a></td><td><button class="btn sm danger" onclick="del('/api/results/${x.id}',results)">삭제</button></td></tr>`).join("")}</tbody></table></div>`;
}
window.viewResult=async id=>{const d=await api(`/api/results/${id}`);modal(d.title,`<div class="actions"><a class="btn primary" href="/api/results/${id}/export?format=docx">DOCX 다운로드</a><a class="btn" href="/api/results/${id}/export?format=pptx">PPTX 다운로드</a><a class="btn" href="/api/results/${id}/export?format=csv">CSV</a><a class="btn" href="/api/results/${id}/export?format=json">JSON</a></div><div style="margin-top:12px">${renderStructured(d.result)}</div>`)}
const schemas={
 leads:{title:"영업 리드",fields:[["company","잠재고객 회사명"],["contact","담당자"],["phone","전화"],["email","이메일"],["stage","단계"],["source","유입경로"],["need","니즈","textarea"],["amount","예상금액","number"],["prob","확률(%)","number"],["next_action","다음 행동"],["next_date","예정일","date"],["memo","메모","textarea"]]},
 tickets:{title:"고객 문의",fields:[["sender","보낸사람"],["email","이메일"],["category","분류"],["priority","우선순위"],["status","상태"],["message","문의내용","textarea"],["draft","AI 답변초안","textarea"],["owner","담당자"]]},
 reports:{title:"경영보고",fields:[["period","기간/주차"],["kpi","KPI/성과","textarea"],["risks","리스크","textarea"],["actions","액션","textarea"],["status","상태"],["memo","메모","textarea"]]},
 automations:{title:"자동화",fields:[["name","자동화명"],["trigger_name","Trigger"],["condition_text","조건","textarea"],["action_text","액션","textarea"],["status","상태"],["owner","담당자"],["notes","메모","textarea"]]}
};
async function generic(name){const a=await api(`/api/${name}`),s=schemas[name];$("#"+name).innerHTML=pageHead(s.title,"상세·수정·삭제",`<button class="btn primary" onclick="editGeneric('${name}')">+ 등록</button>`)+`<div class="card"><table><thead><tr>${s.fields.slice(0,5).map(f=>`<th>${f[1]}</th>`).join("")}<th></th></tr></thead><tbody>${a.map(x=>`<tr>${s.fields.slice(0,5).map(f=>`<td>${esc(x[f[0]]??"")}</td>`).join("")}<td><button class="btn sm" onclick='editGeneric("${name}","${x.id}")'>수정</button> <button class="btn sm danger" onclick="del('/api/${name}/${x.id}',()=>generic('${name}'))">삭제</button></td></tr>`).join("")}</tbody></table></div>`;window["_"+name]=a}
async function leads(){return generic("leads")} async function tickets(){return generic("tickets")} async function reports(){return generic("reports")} async function automations(){return generic("automations")}
window.editGeneric=(name,id)=>{const s=schemas[name],x=id?window["_"+name].find(y=>y.id===id):{};modal((id?"수정 - ":"등록 - ")+s.title,`${name!=="automations"&&me.role==="admin"?`<label>고객사</label><select id="g_client">${clients.map(c=>`<option value="${c.id}" ${x.client_id===c.id?"selected":""}>${esc(c.name)}</option>`).join("")}</select>`:""}${s.fields.map(f=>`<label>${f[1]}</label>${f[2]==="textarea"?`<textarea id="g_${f[0]}">${esc(x[f[0]])}</textarea>`:`<input id="g_${f[0]}" type="${f[2]||"text"}" value="${esc(x[f[0]])}">`}`).join("")}<button class="btn primary" id="saveGeneric">저장</button>`);$("#saveGeneric").onclick=async()=>{const b={};s.fields.forEach(f=>b[f[0]]=$("#g_"+f[0]).value);if(name!=="automations")b.client_id=me.role==="admin"?$("#g_client").value:me.client_id;await api(id?`/api/${name}/${id}`:`/api/${name}`,{method:id?"PUT":"POST",body:JSON.stringify(b)});closeModal();generic(name)}}
async function opportunities(){const a=await api("/api/opportunities");$("#opportunities").innerHTML=pageHead("지원사업·입찰","공고명·발주처·첨부·공고일·마감일·예산·상태·적합도·조건·제출서류",`<button class="btn primary" onclick="editOpp()">+ 공고등록</button>`)+`<div class="card"><table><thead><tr><th>구분/기관</th><th>공고명</th><th>공고일</th><th>마감일</th><th>예산</th><th>Fit</th><th>상태</th><th></th></tr></thead><tbody>${a.map(o=>`<tr><td>${esc(o.type)}<br><span class="muted">${esc(o.issuer)}</span></td><td><b>${esc(o.title)}</b><br><span class="muted">${esc(o.next_action)}</span></td><td>${esc(o.notice_date||"")}</td><td>${esc(o.deadline||"")}</td><td>${esc(o.budget||"")}</td><td>${esc(o.fit)}</td><td>${esc(o.status)}</td><td>${o.attachment_name?`<button class="btn sm" onclick="location.href='/api/opportunities/${o.id}/download'">첨부</button> `:""}<button class="btn sm" onclick='editOpp("${o.id}")'>수정</button> <button class="btn sm danger" onclick="del('/api/opportunities/${o.id}',opportunities)">삭제</button></td></tr>`).join("")}</tbody></table></div>`;window._opps=a}
window.editOpp=id=>{const o=id?window._opps.find(x=>x.id===id):{};modal(id?"공고 수정":"공고 등록",`${me.role==="admin"?`<label>고객사</label><select id="o_client">${clients.map(c=>`<option value="${c.id}" ${o.client_id===c.id?"selected":""}>${esc(c.name)}</option>`).join("")}</select>`:""}<div class="form2"><div><label>구분</label><input id="o_type" value="${esc(o.type||"입찰")}"></div><div><label>발주처/기관</label><input id="o_issuer" value="${esc(o.issuer)}"></div><div><label>공고명 *</label><input id="o_title" value="${esc(o.title)}"></div><div><label>예산/지원규모</label><input id="o_budget" value="${esc(o.budget)}"></div><div><label>공고일</label><input id="o_notice_date" type="date" value="${esc(o.notice_date)}"></div><div><label>마감일</label><input id="o_deadline" type="date" value="${esc(o.deadline)}"></div><div><label>URL</label><input id="o_url" value="${esc(o.url)}"></div><div><label>적합도</label><input id="o_fit" value="${esc(o.fit||"Medium")}"></div><div><label>상태</label><input id="o_status" value="${esc(o.status||"신규")}"></div><div><label>담당자</label><input id="o_manager" value="${esc(o.manager)}"></div><div><label>다음 행동</label><input id="o_next_action" value="${esc(o.next_action)}"></div></div><label>자격/참여조건</label><textarea id="o_eligibility">${esc(o.eligibility)}</textarea><label>제출자료</label><textarea id="o_deliverables">${esc(o.deliverables)}</textarea><label>세부메모</label><textarea id="o_memo">${esc(o.memo)}</textarea>${id?"":`<label>공고 첨부파일</label><input id="o_file" type="file">`}<button class="btn primary" id="saveOpp">저장</button>`);$("#saveOpp").onclick=async()=>{if(id){const b={};["type","issuer","title","budget","notice_date","deadline","url","fit","status","manager","next_action","eligibility","deliverables","memo"].forEach(k=>b[k]=$("#o_"+k).value);await api(`/api/opportunities/${id}`,{method:"PUT",body:JSON.stringify(b)})}else{const f=new FormData();f.append("client_id",me.role==="admin"?$("#o_client").value:me.client_id);["type","issuer","title","budget","notice_date","deadline","url","fit","status","manager","next_action","eligibility","deliverables","memo"].forEach(k=>f.append(k,$("#o_"+k).value));if($("#o_file").files[0])f.append("attachment",$("#o_file").files[0]);await api("/api/opportunities",{method:"POST",body:f})}closeModal();opportunities()}}
async function usage(){const a=await api("/api/usage");$("#usage").innerHTML=pageHead("AI 사용량","질문·결과·토큰 사용내역")+`<div class="card"><table><thead><tr><th>고객사</th><th>역할</th><th>요청</th><th>입력</th><th>출력</th><th>일시</th></tr></thead><tbody>${a.map(x=>`<tr><td>${esc(clients.find(c=>c.id===x.client_id)?.name||"")}</td><td>${esc(x.role)}</td><td>${esc(x.request)}</td><td>${x.input_tokens||0}</td><td>${x.output_tokens||0}</td><td>${esc(x.created_at)}</td></tr>`).join("")}</tbody></table></div>`}
async function del(url,cb){if(!confirm("삭제하시겠습니까?"))return;try{await api(url,{method:"DELETE"});await cb()}catch(e){alert(e.message)}}
$("#loginBtn").onclick=login;$("#logoutBtn").onclick=async()=>{await api("/api/logout",{method:"POST"});location.reload()};boot();
